---
name: "National Rail Departure Board"
version: "1.0.0"
slug: "national-rail-departure-board"
description: "A beautiful departure board for UK railway stations using National Rail data"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  8123/tcp: 8123
webui: "http://[HOST]:[PORT:8123]"
ingress: true
ingress_port: 8123
panel_icon: mdi:train
homeassistant_api: true 