name: "National Rail Departure Board"
version: "1.0.0"
slug: "national-rail-departure-board"
description: "A beautiful departure board for UK railway stations using National Rail data"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  8124/tcp: 8124
webui: "http://[HOST]:[PORT:8124]"
ingress: true
ingress_port: 8124
ingress_entry: /hassio_ingress/national-rail-departure-board
panel_icon: mdi:train
homeassistant_api: true
schema:
  api_key: str
  start_station: str
  destination_station: str
  refresh_interval: int
  max_departures: int
  time_window: int
options:
  api_key: ""
  start_station: "PAD"
  destination_station: ""
  refresh_interval: 60
  max_departures: 10
  time_window: 120 